import type { Metadata } from "next";
import { Roboto_Mono } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";
import { TaskProvider } from "./context/taskContext";

const robotoMono = Roboto_Mono({
  variable: "--font-signika-negative",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Task Flow",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full">
      <body className={`${robotoMono.className} antialiased bg-dark-blue-50 `}>
        <Providers>
          <TaskProvider>{children}</TaskProvider>
        </Providers>
      </body>
    </html>
  );
}
